module JsonBuilder
  def self.encode_string: (String) -> String
  def self.escape_html_entities: (String) -> String
  def self.encode_value: (untyped) -> String
  def self.encode_datetime: (String?) -> String
  def self.encode_string_array: (Array[String]) -> String
  def self.encode_enum: (Array[String], Integer) -> String
end
