//! `rust` library/module emit — `LibraryClass` consumer +
//! Module-mode entry points.
//!
//! Phase 2.1 scope: Module-mode `emit_module` for free-function
//! runtime files (inflector). Library-mode `emit_library_class`
//! comes in Phase 2.2 (HWIA) when struct + impl emit lands.

use std::fmt::Write;

use super::method::{emit_instance_method, emit_module_method};
use super::ty::rust_ty;
use crate::dialect::{LibraryClass, MethodDef, MethodReceiver};
use crate::expr::{Expr, ExprNode, Literal, LValue};
use crate::ty::Ty;

/// Module mode — flat list of `def self.*` helpers (e.g.
/// `inflector.rb`'s `Inflector.pluralize`). Each method emits as a
/// top-level `pub fn`. The output file IS the namespace at the
/// Rust module level (`src/inflector.rs` → `crate::inflector`); no
/// extra `mod NAME { ... }` wrapper needed.
///
/// Mirrors `crystal::emit_module` in role; differs in that crystal
/// requires explicit `module X ... end` wrapping while rust uses
/// the file-as-module convention.
///
/// Module-mode entries bypass the `runtime_loader::transpile_entry`
/// `transform` closure that Library-mode runs (the closure is the
/// hook `rust.rs` uses for `str_color` on Library-mode classes).
/// Apply the same `str_color` pass here so Module-mode methods
/// (router.rb, view_helpers.rb's free functions, etc.) get the
/// same ownership annotations before emit.
pub fn emit_module(methods: &[MethodDef]) -> Result<String, String> {
    if methods.is_empty() {
        return Ok(String::new());
    }
    let mut colored: Vec<MethodDef> = methods.to_vec();
    let registry = crate::emit::rust::decide::str_color::build_registry_from_methods(&colored);
    for m in colored.iter_mut() {
        crate::emit::rust::decide::str_color::color_method(m, &registry);
    }
    // Run the rest of the decide pass (parens, last-use / clone-at)
    // on a single-class wrapper. Mirrors the multi-class call sites
    // in `rust.rs::emit`.
    let mut wrap = vec![crate::dialect::LibraryClass {
        name: crate::ident::ClassId(crate::ident::Symbol::from("__emit_module__")),
        is_module: false,
        parent: None,
        includes: Vec::new(),
        methods: std::mem::take(&mut colored),
        nullable_columns: Vec::new(),
        origin: None,
        constants: Vec::new(),
        unknown_calls: Vec::new(),
        class_ivar_initializers: Vec::new(),
    }];
    super::decide::decide_classes(&mut wrap);
    colored = wrap.into_iter().next().unwrap().methods;
    let mut out = String::new();
    writeln!(out, "// Generated by Roundhouse (rust2).").unwrap();
    writeln!(out).unwrap();
    let mut first = true;
    for m in &colored {
        if !first {
            writeln!(out).unwrap();
        }
        first = false;
        out.push_str(&emit_module_method(m)?);
    }
    Ok(out)
}

/// Library mode — `class Foo ... end` → `pub struct Foo { ... }` +
/// `impl Foo { ... }`. Phase 2.2 lands the scaffold:
///
/// * Ivars are collected from method bodies and emitted as private
///   struct fields. Type comes from each ivar's first observed
///   assignment in the analyzed IR (the body-typer fills `e.ty`);
///   untyped ivars fall back to `serde_json::Value` via `rust_ty`.
/// * Each instance method emits as `pub fn name(&self, ...)` or
///   `pub fn name(&mut self, ...)`. The mutability heuristic walks
///   the body for `@ivar = ...` (LValue::Ivar) or `self[k] = v`
///   (LValue::Index recv=SelfRef) and picks `&mut self` if it sees
///   either.
/// * `def initialize` becomes `pub fn new(...) -> Self`; the
///   construction body is the user's `initialize` body with a final
///   `Self { fields }` return expression.
///
/// Subsequent commits drive the per-ExprNode body emit until the
/// produced Rust is `cargo check`-clean.
pub fn emit_library_class(class: &LibraryClass) -> Result<String, String> {
    // Strip the namespace prefix (`ActiveSupport::HashWithIndifferentAccess`
    // → `HashWithIndifferentAccess`). Rust uses file-as-module, so the
    // namespace is carried by the file path, not the struct name.
    let name = class
        .name
        .0
        .as_str()
        .rsplit("::")
        .next()
        .unwrap_or(class.name.0.as_str())
        .to_string();

    let ivars = collect_ivar_types(&class.methods);

    // Module-singleton classes (Ruby `class << self; attr_accessor
    // :slot; end` inside a `module X`) have only class methods —
    // their "ivars" are module-level state, not per-instance fields.
    // Rust analog: unit struct + per-slot `Mutex<Option<T>>` statics.
    // Detection: every method has Class receiver and the class isn't
    // empty (the empty-class case is just a marker, e.g. `module X;
    // end`, and falls through to the regular struct emit shape).
    let is_module_singleton = !class.methods.is_empty()
        && class
            .methods
            .iter()
            .all(|m| matches!(m.receiver, MethodReceiver::Class));
    if is_module_singleton {
        return emit_module_singleton(&name, &ivars, class);
    }

    // Pre-pass: identify methods whose body never reads `self` or
    // any `@ivar`. Those are static-safe — emit as `pub fn name(...)`
    // (no `self` receiver) so they're callable from `new` before an
    // instance exists. HWIA's `normalize_value` is the canonical
    // case: pure value-transformation, no instance state. The
    // companion call-site rewrite in `expr.rs::emit_send` routes
    // `self.method(args)` for these methods to `Self::method(args)`.
    let static_method_names: std::collections::HashSet<String> = class
        .methods
        .iter()
        .filter(|m| {
            matches!(m.receiver, MethodReceiver::Instance)
                && m.name.as_str() != "initialize"
                && !method_reads_self(&m.body)
                // Abstract-stub bodies (just `raise NotImplementedError`)
                // are the per-class contract markers. They don't read
                // self by construction, but per-model subclasses override
                // them — and callers reach the overrides through
                // instance dispatch (`record.dom_prefix()`). Classify
                // those as `&self` methods so the call site resolves.
                && !is_raise_only_body(&m.body)
                // The OVERRIDES of those markers get the same shape by
                // NAME: a non-STI model's `dom_prefix` body is a bare
                // string literal (reads no self), but the broadcast
                // lowerings call it through a typed receiver
                // (`parent.dom_prefix()`), and a static override of an
                // instance contract strands that call site.
                && !matches!(m.name.as_str(), "dom_prefix" | "dom_record_key" | "to_param")
        })
        .map(|m| m.name.as_str().to_string())
        .collect();

    // `mutates_self` flag is filled by `analyze::mutates_self::propagate`
    // alongside the str_color pass in `emit/rust.rs`'s transform
    // closure. Build the per-class mutating-name set from the flags
    // for the `static_method_names` exclusion check + the existing
    // call-site method-mutates logic that the body emit consults.
    let mutating_methods: std::collections::HashSet<String> = class
        .methods
        .iter()
        .filter(|m| m.mutates_self)
        .map(|m| m.name.as_str().to_string())
        .collect();

    let mut out = String::new();

    // Struct declaration. Derive `Clone` because Ruby semantics treat
    // model instances as freely cloneable (every assignment and
    // method-call argument-pass implicitly copies a reference, and
    // the framework Ruby's `attr_reader` getters and `.dup` patterns
    // expect to hand out independent copies). Each ivar type must
    // itself be Clone — every type rust emits today (i64, String,
    // bool, Vec<T: Clone>, HashMap<String, serde_json::Value>,
    // Option<T: Clone>, Class names → Clone'd) satisfies that.
    //
    // Also derive `Default` so axum-wrapper-emitted code can
    // `<Controller>::default()`-construct a controller with empty
    // params + flash + zeroed model ivars (wedge 2c). Every Rust
    // primitive type (i64/bool/f64/String) is Default; container
    // types (Vec/HashMap/Option) too; and the lowerer-emitted
    // model classes — Article, Comment, Row holders, Params
    // resources — are themselves marked `#[derive(Default)]` by
    // this same path, so the derive cascades through cross-model
    // ivar references. If a future non-Default ivar lands, this
    // derive will fail at compile time and we'll need a per-class
    // override.
    writeln!(out, "#[derive(Clone, Default)]").unwrap();
    writeln!(out, "pub struct {name} {{").unwrap();
    // Fields are `pub` so legacy-emit-style controller test bodies
    // (`@article.title`, `Article.last.id`) — which use field
    // access syntax rather than getter method calls — resolve
    // against the same struct. The lowerer-emitted instance
    // methods (`title(&self) -> String { self.title.clone() }`)
    // still work alongside; Rust disambiguates field vs method
    // by trailing parens at the call site.
    for (fname, ty) in &ivars {
        writeln!(out, "    pub {fname}: {},", rust_ty(ty)).unwrap();
    }
    out.push_str("}\n\n");

    // Impl block. Each method renders independently; `initialize`
    // routes through the constructor variant of `emit_instance_method`.
    // `def self.X` class methods emit as `pub fn name(...)` (no
    // receiver) — Rust's free-function-in-impl form. Callers reach
    // them via `Type::name(...)`, same dispatch path static-safe
    // instance methods use.
    writeln!(out, "impl {name} {{").unwrap();
    let mut first = true;
    // Make this class's ivar → field-type table available to
    // `emit_assign` (via thread-local) so RHS values can be coerced
    // when their Ty doesn't match the declared field type — most
    // commonly `self.body = ""` where field is `String` and `""` is
    // `&str`. Empty outside class-body scope; scoped per-class to
    // prevent bleeding between siblings.
    let ivar_type_map: std::collections::HashMap<String, Ty> =
        ivars.iter().cloned().collect();
    let class_method_param_tys = collect_class_method_param_tys(&class.methods);
    let body_result = super::expr::with_class_method_param_tys(class_method_param_tys, || super::expr::with_ivar_types(ivar_type_map, || super::expr::with_static_methods(static_method_names.clone(), || {
        for m in &class.methods {
            if !first {
                writeln!(out).unwrap();
            }
            first = false;
            let body = match m.receiver {
                MethodReceiver::Class => {
                    // `def self.X` → `pub fn X(...)` with no receiver.
                    // Module-style call from within the impl block.
                    super::method::emit_module_method(m)?
                }
                MethodReceiver::Instance => {
                    let is_static = static_method_names.contains(m.name.as_str());
                    let mutates = mutating_methods.contains(m.name.as_str());
                    emit_instance_method(m, mutates, is_static, &name, &ivars)?
                }
            };
            for line in body.lines() {
                if line.is_empty() {
                    writeln!(out).unwrap();
                } else {
                    writeln!(out, "    {line}").unwrap();
                }
            }
        }
        Ok::<(), String>(())
    })));
    body_result?;
    if name == "Base"
        && class
            .methods
            .iter()
            .any(|m| m.name.as_str() == "render")
    {
        // 2-arg `self.render(body, opts)` rewrites to `render_with`.
        // Controller subclasses get that shim from rust.rs; Base
        // itself must unpack opts onto its 4-arg `render`.
        writeln!(out).unwrap();
        writeln!(
            out,
            "    pub fn render_with(&mut self, content: &str, opts: std::collections::HashMap<String, serde_json::Value>) {{"
        )
        .unwrap();
        writeln!(
            out,
            "        let status = opts.get(\"status\").and_then(|v| v.as_str()).unwrap_or(\"ok\");"
        )
        .unwrap();
        writeln!(out, "        self.render(content, status, None, None);").unwrap();
        writeln!(out, "    }}").unwrap();
    }
    out.push_str("}\n");
    Ok(out)
}

/// Module singletons whose state is *per-request render state*, not
/// process-wide configuration. Their ivar slots emit as `thread_local!`
/// `RefCell<Option<T>>` instead of a global `Mutex<Option<T>>`.
///
/// Why: `ViewHelpers`' content_for/yield slot store is reset and
/// repopulated on every request. Behind a process-global mutex, every
/// concurrent render serializes on one lock — profiled at c=64 as
/// ~46% of thread-time blocked in mutex wait on the no-DB
/// `/articles/new` endpoint (roundhouse#32); switching to
/// thread-locals measured +24% throughput. Thread-locals are correct
/// here because a request's render runs synchronously inside one
/// handler poll (controller action → views → layout, no `.await`
/// between `set_yield` and `get_yield`), so the state never needs to
/// cross threads. This mirrors Rails' own per-thread scoping of view
/// rendering state (and the hand-written `runtime/rust/view_helpers.rs`,
/// which used `thread_local!` before the framework runtime moved to
/// transpiled Ruby).
///
/// Config-like singletons (`ActiveRecord`'s ADAPTER: set once at boot
/// from the main thread, read from every worker) must stay global, so
/// global-Mutex remains the default and this list is opt-in. The
/// durable fix — threading an `ActionView::Slots` value object
/// per-request — is tracked in runtime/ruby/action_view/view_helpers.rb's
/// header comment; this list is the call surface's interim shape.
const REQUEST_SCOPED_SINGLETONS: &[&str] = &["ViewHelpers"];

fn is_request_scoped_singleton(name: &str) -> bool {
    REQUEST_SCOPED_SINGLETONS.contains(&name)
}

/// Emit a Ruby `module X; class << self; attr_accessor :slot; end;
/// end` class as a Rust unit struct + per-slot `Mutex<Option<T>>`
/// statics (or `thread_local!` `RefCell<Option<T>>` for
/// request-scoped singletons — see `REQUEST_SCOPED_SINGLETONS`).
/// The transpiled `attr_accessor` getter/setter pair routes
/// through the static slot (see `expr.rs::in_module_singleton`).
///
/// Produces:
///
/// ```text
/// pub struct ActiveRecord;
///
/// static ADAPTER: std::sync::Mutex<Option<Value>> =
///     std::sync::Mutex::new(None);
///
/// impl ActiveRecord {
///     pub fn adapter() -> Value { ... }
///     pub fn set_adapter(value: Value) { ... }
/// }
/// ```
fn emit_module_singleton(
    name: &str,
    ivars: &[(String, Ty)],
    class: &LibraryClass,
) -> Result<String, String> {
    let thread_local = is_request_scoped_singleton(name);
    let mut out = String::new();
    // Unit struct — no per-instance fields. Callers reach the slot
    // methods via `ActiveRecord::adapter()` / `ActiveRecord::set_adapter(v)`.
    writeln!(out, "pub struct {name};\n").unwrap();
    // One slot static per ivar. Naming follows the SCREAMING_SNAKE
    // Rust static convention; trim_start_matches('_') handles
    // leading-underscore ivars. Request-scoped singletons get
    // `thread_local!` `RefCell<Option<T>>` slots; everything else a
    // process-global `Mutex<Option<T>>`.
    if thread_local && !ivars.is_empty() {
        writeln!(out, "thread_local! {{").unwrap();
        for (fname, ty) in ivars {
            let slot = super::expr::module_singleton_slot_name(fname);
            writeln!(
                out,
                "    static {slot}: std::cell::RefCell<Option<{}>> = const {{ std::cell::RefCell::new(None) }};",
                rust_ty(ty),
            )
            .unwrap();
        }
        writeln!(out, "}}").unwrap();
    } else {
        for (fname, ty) in ivars {
            let slot = super::expr::module_singleton_slot_name(fname);
            writeln!(
                out,
                "static {slot}: std::sync::Mutex<Option<{}>> = std::sync::Mutex::new(None);",
                rust_ty(ty),
            )
            .unwrap();
        }
    }
    if !ivars.is_empty() {
        out.push('\n');
    }
    writeln!(out, "impl {name} {{").unwrap();
    let ivar_type_map: std::collections::HashMap<String, Ty> =
        ivars.iter().cloned().collect();
    let class_method_param_tys = collect_class_method_param_tys(&class.methods);
    let body_result = super::expr::with_class_method_param_tys(class_method_param_tys, || super::expr::with_module_singleton(true, thread_local, || {
        super::expr::with_ivar_types(ivar_type_map, || {
            let mut first = true;
            for m in &class.methods {
                if matches!(m.name.as_str(), "[]" | "[]=") {
                    continue;
                }
                if !first {
                    writeln!(out).unwrap();
                }
                first = false;
                // Module-singleton methods are class methods by
                // construction (detection in `emit_library_class`).
                let body = super::method::emit_module_method(m)?;
                for line in body.lines() {
                    if line.is_empty() {
                        writeln!(out).unwrap();
                    } else {
                        writeln!(out, "    {line}").unwrap();
                    }
                }
            }
            Ok::<(), String>(())
        })
    }));
    body_result?;
    out.push_str("}\n");
    Ok(out)
}

/// `true` when the method body is a bare `raise X` call. The ingest
/// pipeline parses Ruby `raise NotImplementedError, "..."` as
/// `Send { recv: None, method: "raise", args: [...] }`, NOT as
/// `ExprNode::Raise` (which is unused in this codebase). Abstract-
/// contract stubs (the `raise NotImplementedError, "..."` convention
/// in `runtime/ruby/`) satisfy this — they're meant to be overridden,
/// and call sites reach the overrides through `record.method()`
/// instance dispatch. Classifying those as static would break that
/// dispatch path (associated-function call form only).
fn is_raise_only_body(body: &Expr) -> bool {
    fn is_raise_send(e: &Expr) -> bool {
        matches!(
            &*e.node,
            ExprNode::Send { recv: None, method, .. } if method.as_str() == "raise"
        )
    }
    match &*body.node {
        ExprNode::Send { recv: None, method, .. } if method.as_str() == "raise" => true,
        ExprNode::Seq { exprs } if exprs.len() == 1 => is_raise_send(&exprs[0]),
        _ => false,
    }
}

/// Static-method probe: returns `true` when the method body
/// references `self` (any `Ivar` read/write or `SelfRef` use). The
/// pre-pass in `emit_library_class` filters this down to methods
/// that can be lifted to `pub fn name(...)` (no `&self`).
fn method_reads_self(body: &Expr) -> bool {
    fn walk(e: &Expr) -> bool {
        match &*e.node {
            ExprNode::SelfRef | ExprNode::Ivar { .. } => true,
            ExprNode::Assign { target, value } => {
                if matches!(target, LValue::Ivar { .. }) {
                    return true;
                }
                if let LValue::Attr { recv, .. } | LValue::Index { recv, .. } = target {
                    if walk(recv) { return true; }
                }
                walk(value)
            }
            ExprNode::Seq { exprs } => exprs.iter().any(walk),
            ExprNode::If { cond, then_branch, else_branch } => {
                walk(cond) || walk(then_branch) || walk(else_branch)
            }
            ExprNode::While { cond, body, .. } => walk(cond) || walk(body),
            ExprNode::Send { recv, args, block, .. } => {
                recv.as_ref().map(|r| walk(r)).unwrap_or(false)
                    || args.iter().any(walk)
                    || block.as_ref().map(|b| walk(b)).unwrap_or(false)
            }
            ExprNode::Return { value } => walk(value),
            ExprNode::StringInterp { parts } => parts.iter().any(|p| {
                if let crate::expr::InterpPart::Expr { expr } = p { walk(expr) } else { false }
            }),
            ExprNode::Hash { entries, .. } => entries.iter().any(|(k, v)| walk(k) || walk(v)),
            ExprNode::Array { elements, .. } => elements.iter().any(walk),
            // `||` / `&&` short-circuit expressions. Without this arm
            // a body like `label || @model_name` short-circuits the
            // self-detection: walk falls into the catch-all `_` arm
            // and returns false, so the method gets misclassified as
            // static-safe (FormBuilder.submit was the visible case —
            // 3 E0424 errors from the missing &self receiver).
            ExprNode::BoolOp { left, right, .. } => walk(left) || walk(right),
            ExprNode::Lambda { body, .. } => walk(body),
            ExprNode::Range { begin, end, .. } => {
                begin.as_ref().map(|b| walk(b)).unwrap_or(false)
                    || end.as_ref().map(|e| walk(e)).unwrap_or(false)
            }
            ExprNode::Yield { args } => args.iter().any(walk),
            // `case scrutinee; when …; body; end` — the per-arm
            // bodies + scrutinee can reach self via Ivar reads or
            // direct self-references. Lowerer-synthesized
            // `get_index` / `set_index` are the canonical case
            // (each arm reads/writes a `@col` Ivar); without this
            // arm both methods misclassified as static and emitted
            // without a `&self` receiver, blowing every Ivar
            // reference into E0424.
            ExprNode::Case { scrutinee, arms } => {
                walk(scrutinee) || arms.iter().any(|a| walk(&a.body))
            }
            ExprNode::Cast { value, .. } => walk(value),
            _ => false,
        }
    }
    walk(body)
}

/// Walk all methods collecting `@ivar = …` assignments. Returns the
/// observed ivar set with each entry's inferred type (the analyzer
/// fills `Expr.ty` during typing; an unset `ty` falls back to
/// `Ty::Untyped` and renders as `serde_json::Value`).
/// Build a `method_name → positional_param_Tys` map for one class.
/// Block + keyword-rest params are filtered out so the call-site
/// positional index lines up with the resulting vector. Used by
/// `with_class_method_param_tys` to seed the callee-back-propagation
/// lookup in emit_send for `Self::method(args)` calls.
fn collect_class_method_param_tys(
    methods: &[MethodDef],
) -> std::collections::HashMap<String, Vec<Ty>> {
    use crate::ty::ParamKind;
    let mut out = std::collections::HashMap::new();
    for m in methods {
        let tys: Vec<Ty> = match m.signature.as_ref() {
            Some(Ty::Fn { params, .. }) => params
                .iter()
                .filter(|p| !matches!(p.kind, ParamKind::Block | ParamKind::KeywordRest))
                .map(|p| p.ty.clone())
                .collect(),
            _ => continue,
        };
        // Ruby `Class.new(args)` invokes `initialize(args)`; the IR
        // call site uses "new" but the body's MethodDef.name is
        // "initialize". Alias so `current_class_method_param_tys
        // ("new")` resolves at `Self::new(...)` / `Article::new(...)`
        // call sites (closes E0061 arity checks like the lowerer-
        // synthesized `from_row` calling `Article.new` zero-arg).
        if m.name.as_str() == "initialize" {
            out.insert("new".to_string(), tys.clone());
        }
        out.insert(m.name.as_str().to_string(), tys);
    }
    out
}

fn collect_ivar_types(methods: &[MethodDef]) -> Vec<(String, Ty)> {
    // Phase 1: walk every method body and record every Ty observed
    // assigning to each ivar — both direct `@x =` (Ivar lvalue) and
    // `self.x = ...` (Attr lvalue with SelfRef recv, which writes the
    // same backing field on the emitted struct). Preserve first-seen
    // order so the struct's field declaration order matches the
    // source's `def initialize` order.
    //
    // Two passes:
    //   pass 1 — walk_collect_ivars records writes (assignments)
    //   pass 2 — walk_collect_ivar_reads records reads ONLY for ivars
    //            with zero writes (inherited-from-parent surface like
    //            controller `@flash`/`@session`/`@params`, which AC::
    //            Base writes from outside the controller class body).
    // Without the read-pass, the struct emit omits inherited fields
    // and downstream `self.flash[:notice] = ...` hits E0609. With
    // read-pass that doesn't gate on no-writes, ivars already typed
    // by writes get widened by re-observation and break framework
    // runtime emit (e.g. `Base.flash` typed Option<Flash> mistakenly).
    let mut order: Vec<String> = Vec::new();
    let mut observed: std::collections::HashMap<String, Vec<Ty>> =
        std::collections::HashMap::new();
    for m in methods {
        walk_collect_ivars(&m.body, &mut order, &mut observed);
    }
    let written: std::collections::HashSet<String> =
        observed.keys().cloned().collect();
    for m in methods {
        walk_collect_ivar_reads(&m.body, &written, &mut order, &mut observed);
    }
    // Phase 2: unify each ivar's observed-type list into one Ty.
    // Rules:
    //   - {Nil, T, ...}            → Option<T> (T = first non-Nil)
    //   - {Nil}                    → Option<Untyped> (nil-only ivar,
    //                                widen to Option for setter shape)
    //   - {Hash<_,_>, Hash<K, V>}  → keep the widest (matches the
    //                                previous one-shot widening for
    //                                empty-literal seeded hashes)
    //   - {T}                      → T (single-type ivar)
    //   - {T1, T2, ...} mixed      → first observed (fallback)
    order
        .into_iter()
        .map(|name| {
            let tys = observed.remove(&name).unwrap_or_default();
            let unified = unify_ivar_tys(&tys);
            (name, unified)
        })
        .collect()
}

fn unify_ivar_tys(tys: &[Ty]) -> Ty {
    let has_nil = tys.iter().any(|t| matches!(t, Ty::Nil));
    let first_non_nil = tys.iter().find(|t| !matches!(t, Ty::Nil)).cloned();
    if has_nil {
        match first_non_nil {
            // Already nilable — a nullable column's slot type is
            // `Union{[T, Nil]}` at every write site, and observing a
            // bare `Nil` alongside it (the initialize seed) must not
            // wrap it again into `Option<Option<T>>`.
            Some(t @ Ty::Union { .. })
                if matches!(&t, Ty::Union { variants } if variants.iter().any(|v| matches!(v, Ty::Nil))) =>
            {
                t
            }
            Some(t) => Ty::Union {
                variants: vec![Ty::Nil, t],
            },
            // Nil-only ivar (e.g. `@location = nil` with no other
            // assignments visible in the class body) — widen to
            // Option<Untyped> so the setter side can assign any
            // value-typed payload without an E0308. Without widening
            // the field types as `()` and every other path fails.
            None => Ty::Union {
                variants: vec![Ty::Nil, Ty::Untyped],
            },
        }
    } else {
        // No Nil observed — pick the most informative concrete type.
        // For Hash, prefer the most-specified variant (Hash{K, V} with
        // concrete K/V over Hash{Untyped, Untyped}) — matches the
        // previous single-shot widening.
        tys.iter()
            .max_by_key(|t| match t {
                Ty::Hash { key, value } => {
                    let k = !matches!(**key, Ty::Untyped);
                    let v = !matches!(**value, Ty::Untyped);
                    (k as u8) + (v as u8)
                }
                // Empty `[]` seeds Array[Untyped]; a later `ivar << s`
                // (HeaderStore `@keys << key`) is Array[String]. Prefer
                // the concrete elem so rust emits `Vec<String>` not
                // `Vec<Value>`.
                Ty::Array { elem } => {
                    if matches!(elem.as_ref(), Ty::Untyped) {
                        1
                    } else {
                        2
                    }
                }
                _ => 0,
            })
            .cloned()
            .unwrap_or(Ty::Untyped)
    }
}

fn walk_collect_ivars(
    e: &Expr,
    order: &mut Vec<String>,
    observed: &mut std::collections::HashMap<String, Vec<Ty>>,
) {
    fn record(
        name: &str,
        ty: Ty,
        order: &mut Vec<String>,
        observed: &mut std::collections::HashMap<String, Vec<Ty>>,
    ) {
        let k = name.to_string();
        if !order.iter().any(|n| n == &k) {
            order.push(k.clone());
        }
        observed.entry(k).or_default().push(ty);
    }
    match &*e.node {
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            let ty = value.ty.clone().unwrap_or(Ty::Untyped);
            record(name.as_str(), ty, order, observed);
            walk_collect_ivars(value, order, observed);
        }
        // `self.x = value` — Attr lvalue with SelfRef recv. Writes
        // the same backing field as `@x = value`. Without this, an
        // ivar assigned only as `@x = nil` in `initialize` and then
        // `self.x = path` in `redirect_to` would type as `()`,
        // mismatching every `self.x = path` site.
        ExprNode::Assign {
            target: LValue::Attr { recv, name },
            value,
        } if matches!(&*recv.node, ExprNode::SelfRef) => {
            let ty = value.ty.clone().unwrap_or(Ty::Untyped);
            record(name.as_str(), ty, order, observed);
            walk_collect_ivars(value, order, observed);
        }
        // `@ivar[k] = v` — Ruby parses as Send `[]=` on Ivar recv.
        // The empty-literal `@data = {}` types as `Hash<Untyped,
        // Untyped>` from analyzer inference; subsequent index-assigns
        // tell us the real key/value types. Only record a Hash
        // observation when the ivar's prior observations already
        // contain a Hash — otherwise `@flash[:notice] = "..."` (where
        // `@flash` is the typed `Flash` struct, not a HashMap) would
        // be misread as a Hash assignment and widen the ivar type
        // away from the concrete struct.
        ExprNode::Send { recv: Some(recv), method, args, .. }
            if method.as_str() == "<<" && args.len() == 1 =>
        {
            if let ExprNode::Ivar { name } = &*recv.node {
                let elem = args[0].ty.clone().unwrap_or(Ty::Untyped);
                record(
                    name.as_str(),
                    Ty::Array {
                        elem: Box::new(elem),
                    },
                    order,
                    observed,
                );
            }
            walk_collect_ivars(recv, order, observed);
            args.iter().for_each(|a| walk_collect_ivars(a, order, observed));
        }
        ExprNode::Send { recv: Some(recv), method, args, .. }
            if method.as_str() == "[]=" && args.len() == 2 =>
        {
            if let ExprNode::Ivar { name } = &*recv.node {
                let key = name.as_str();
                let already_hash = observed
                    .get(key)
                    .map(|tys| tys.iter().any(|t| matches!(t, Ty::Hash { .. })))
                    .unwrap_or(false);
                if already_hash {
                    let k_ty = args[0].ty.clone().unwrap_or(Ty::Untyped);
                    let v_ty = args[1].ty.clone().unwrap_or(Ty::Untyped);
                    record(
                        key,
                        Ty::Hash {
                            key: Box::new(k_ty),
                            value: Box::new(v_ty),
                        },
                        order,
                        observed,
                    );
                }
            }
            walk_collect_ivars(recv, order, observed);
            args.iter().for_each(|a| walk_collect_ivars(a, order, observed));
        }
        ExprNode::Seq { exprs } => {
            exprs.iter().for_each(|e| walk_collect_ivars(e, order, observed))
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            walk_collect_ivars(cond, order, observed);
            walk_collect_ivars(then_branch, order, observed);
            walk_collect_ivars(else_branch, order, observed);
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv { walk_collect_ivars(r, order, observed); }
            args.iter().for_each(|a| walk_collect_ivars(a, order, observed));
            if let Some(b) = block { walk_collect_ivars(b, order, observed); }
        }
        ExprNode::While { cond, body, .. } => {
            walk_collect_ivars(cond, order, observed);
            walk_collect_ivars(body, order, observed);
        }
        ExprNode::Return { value } => walk_collect_ivars(value, order, observed),
        _ => {}
    }
}

/// Second-pass walk that records ivar READS (not writes) — only for
/// ivars NOT already observed via writes. Closes the inherited-ivar
/// gap for controllers (`@flash`, `@session`, `@params` set by AC::
/// Base, read inside actions). Ivars with at least one write skip
/// this pass entirely — the write-based ty rules already cover them.
fn walk_collect_ivar_reads(
    e: &Expr,
    written: &std::collections::HashSet<String>,
    order: &mut Vec<String>,
    observed: &mut std::collections::HashMap<String, Vec<Ty>>,
) {
    fn record(
        name: &str,
        ty: Ty,
        order: &mut Vec<String>,
        observed: &mut std::collections::HashMap<String, Vec<Ty>>,
    ) {
        let k = name.to_string();
        if !order.iter().any(|n| n == &k) {
            order.push(k.clone());
        }
        observed.entry(k).or_default().push(ty);
    }
    match &*e.node {
        ExprNode::Ivar { name } => {
            let n = name.as_str();
            if !written.contains(n) {
                if let Some(ty) = e.ty.as_ref() {
                    if !ty.is_unknown() {
                        record(n, ty.clone(), order, observed);
                    }
                }
            }
        }
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => {
            walk_collect_ivar_reads(value, written, order, observed);
        }
        ExprNode::Assign {
            target: LValue::Attr { recv, .. },
            value,
        } if matches!(&*recv.node, ExprNode::SelfRef) => {
            walk_collect_ivar_reads(value, written, order, observed);
        }
        ExprNode::Seq { exprs } => {
            exprs.iter().for_each(|e| walk_collect_ivar_reads(e, written, order, observed))
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            walk_collect_ivar_reads(cond, written, order, observed);
            walk_collect_ivar_reads(then_branch, written, order, observed);
            walk_collect_ivar_reads(else_branch, written, order, observed);
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv { walk_collect_ivar_reads(r, written, order, observed); }
            args.iter().for_each(|a| walk_collect_ivar_reads(a, written, order, observed));
            if let Some(b) = block { walk_collect_ivar_reads(b, written, order, observed); }
        }
        ExprNode::While { cond, body, .. } => {
            walk_collect_ivar_reads(cond, written, order, observed);
            walk_collect_ivar_reads(body, written, order, observed);
        }
        ExprNode::Return { value } => walk_collect_ivar_reads(value, written, order, observed),
        _ => {}
    }
}

/// Top-level constant declaration. Crystal: `NAME = VALUE`. TS:
/// `const NAME = VALUE;`. Rust picks a declaration shape per value
/// kind — `pub const NAME: T = V;` for scalars, `static NAME:
/// LazyLock<HashMap<K, V>> = LazyLock::new(|| HashMap::from([...]))`
/// for Hash literals, `static NAME: LazyLock<Regex> = LazyLock::new(|| ...)`
/// for regex literals. Fully-qualified paths (`std::sync::LazyLock`,
/// `regex::Regex`) avoid per-file imports — the rust emit table
/// doesn't pre-declare them and constants are emitted before classes.
pub fn format_constant(name: &str, value: &Expr) -> String {
    match &*value.node {
        ExprNode::Lit { value: Literal::Int { value: v } } => {
            format!("pub const {name}: i64 = {v}_i64;")
        }
        ExprNode::Lit { value: Literal::Float { value: v } } => {
            let s = v.to_string();
            let lit = if s.contains('.') { s } else { format!("{s}.0") };
            format!("pub const {name}: f64 = {lit};")
        }
        ExprNode::Lit { value: Literal::Bool { value: v } } => {
            format!("pub const {name}: bool = {v};")
        }
        ExprNode::Lit { value: Literal::Str { value: v } } => {
            format!("pub const {name}: &str = {v:?};")
        }
        ExprNode::Lit { value: Literal::Sym { value: v } } => {
            format!("pub const {name}: &str = {:?};", v.as_str())
        }
        ExprNode::Lit { value: Literal::Regex { pattern, .. } } => {
            // Use a raw string for the pattern so backslashes don't
            // need re-escaping. Ruby's regex syntax differs from
            // Rust's regex crate in some edge cases (lookbehind,
            // named captures); the framework Ruby's regex usage is
            // limited to character classes today, which both crates
            // share.
            format!(
                "static {name}: std::sync::LazyLock<regex::Regex> = \
                 std::sync::LazyLock::new(|| regex::Regex::new({pattern:?}).unwrap());"
            )
        }
        ExprNode::Hash { entries, .. } => format_hash_constant(name, entries),
        ExprNode::Array { elements, .. } => format_array_constant(name, elements),
        _ => format!("// TODO rust2 const: {name} = {:?}", value.node),
    }
}

fn format_hash_constant(name: &str, entries: &[(Expr, Expr)]) -> String {
    // Infer key/value types from the first entry. The body-typer's
    // Hash literal inference unifies across entries, so all keys and
    // all values share a type — sampling [0] is enough.
    let (key_ty, val_ty) = match entries.first() {
        Some((k, v)) => (rust_ty_for_constant_key(k), rust_ty_for_constant(v)),
        None => ("&'static str".to_string(), "&'static str".to_string()),
    };
    let mut pairs: Vec<String> = Vec::new();
    for (k, v) in entries {
        let k_s = render_constant_key(k);
        let v_s = render_constant_value(v);
        pairs.push(format!("({k_s}, {v_s})"));
    }
    let pairs_s = pairs.join(", ");
    format!(
        "static {name}: std::sync::LazyLock<std::collections::HashMap<{key_ty}, {val_ty}>> = \
         std::sync::LazyLock::new(|| std::collections::HashMap::from([{pairs_s}]));"
    )
}

fn format_array_constant(name: &str, elements: &[Expr]) -> String {
    let elem_ty = match elements.first() {
        Some(e) => rust_ty_for_constant(e),
        None => "&'static str".to_string(),
    };
    let items: Vec<String> = elements.iter().map(render_constant_value).collect();
    let items_s = items.join(", ");
    format!(
        "static {name}: std::sync::LazyLock<std::sync::Mutex<Vec<{elem_ty}>>> = \
         std::sync::LazyLock::new(|| std::sync::Mutex::new(vec![{items_s}]));"
    )
}

/// Hash key type — Symbol/String keys both become `&'static str` so
/// `HashMap::get(&key)` from a runtime `&str` resolves. Other key
/// shapes fall back to the value-type rule (untested but mechanical).
fn rust_ty_for_constant_key(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value: Literal::Sym { .. } } | ExprNode::Lit { value: Literal::Str { .. } } => {
            "&'static str".to_string()
        }
        _ => rust_ty_for_constant(e),
    }
}

fn rust_ty_for_constant(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value: Literal::Int { .. } } => "i64".to_string(),
        ExprNode::Lit { value: Literal::Float { .. } } => "f64".to_string(),
        ExprNode::Lit { value: Literal::Bool { .. } } => "bool".to_string(),
        ExprNode::Lit { value: Literal::Str { .. } } => "&'static str".to_string(),
        ExprNode::Lit { value: Literal::Sym { .. } } => "&'static str".to_string(),
        _ => "&'static str".to_string(),
    }
}

/// Render a constant key (Hash) as a Rust expression. Symbol keys
/// become string literals (matching Ruby's source-level
/// `Symbol#to_s`); string keys quote with `{:?}`-style escaping.
fn render_constant_key(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
        _ => render_constant_value(e),
    }
}

fn render_constant_value(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value: Literal::Int { value } } => format!("{value}_i64"),
        ExprNode::Lit { value: Literal::Float { value } } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        ExprNode::Lit { value: Literal::Bool { value } } => value.to_string(),
        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
        ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
        _ => format!("/* TODO rust2 const value: {:?} */", e.node),
    }
}

#[cfg(test)]
mod op_assign_tests {
    use super::emit_library_class;

    fn emit(ruby: &str, rbs: &str) -> String {
        let classes = crate::runtime_src::parse_library_with_rbs(ruby.as_bytes(), rbs, "op_assign.rb")
            .expect("snippet parses and types");
        crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes.iter().map(|c| emit_library_class(c).expect("emits")).collect()
        })
    }

    /// `+=` used to fall through the expression catch-all, which dropped
    /// the statement: a `while i < n; …; i += 1; end` counter never
    /// advanced, and the transpiled loop spun forever.
    #[test]
    fn op_assign_emits_the_assignment() {
        let out = emit(
            "module OpAssign\n  def self.count(n)\n    i = 0\n    s = \"\"\n    while i < n\n      s += \"x\"\n      i += 1\n    end\n    s\n  end\nend\n",
            "module OpAssign\n  def self.count: (Integer n) -> String\nend\n",
        );
        assert!(!out.contains("TODO rust2"), "OpAssign fell through:\n{out}");
        assert!(out.contains("i = i + 1_i64"), "int counter not advanced:\n{out}");
        // A `+=` is a reassignment, so its local needs `let mut` as the
        // spelled-out `s = s + "x"` gets.
        assert!(out.contains("let mut s"), "`+=` local not declared mut:\n{out}");
    }
}

#[cfg(test)]
mod value_union_emit_tests {
    use super::emit_library_class;

    fn emit(ruby: &str, rbs: &str) -> String {
        let classes = crate::runtime_src::parse_library_with_rbs(ruby.as_bytes(), rbs, "value_union.rb")
            .expect("snippet parses and types");
        crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes.iter().map(|c| emit_library_class(c).expect("emits")).collect()
        })
    }

    /// Heterogeneous RBS unions rust-emit as `serde_json::Value`. Display
    /// JSON-quotes strings; interpolation must use `ruby_to_s`.
    #[test]
    fn value_shaped_interpolation_uses_ruby_to_s() {
        let out = emit(
            r#"module ValueUnion
  def self.wrap(value)
    "[#{value}]"
  end
end
"#,
            r#"module ValueUnion
  def self.wrap: (String | Integer | Float | bool | nil value) -> String
end
"#,
        );
        assert!(
            out.contains("ruby_to_s"),
            "Value-shaped interp must not use Display JSON quotes:\n{out}"
        );
    }

    /// Hash#fetch(k, nil) peepholes to `Option<Value>`. A stringish param
    /// must materialize Null-on-miss before `.as_str()`.
    #[test]
    fn fetch_nil_at_string_param_materializes_owned_value() {
        let out = emit(
            r#"module ValueUnion
  def self.take_str(s)
    s
  end
  def self.escape_fetch(opts)
    take_str(opts.fetch(:title, nil))
  end
end
"#,
            r#"module ValueUnion
  def self.take_str: (String s) -> String
  def self.escape_fetch: (Hash[Symbol, untyped] opts) -> String
end
"#,
        );
        assert!(
            out.contains("unwrap_or(serde_json::Value::Null)") && out.contains("as_str()"),
            "fetch-nil at a String param must not call as_str on Option:\n{out}"
        );
    }

    fn emit_view_helpers() -> String {
        let ruby = include_str!("../../../runtime/ruby/action_view/view_helpers.rb");
        let rbs = include_str!("../../../runtime/ruby/action_view/view_helpers.rbs");
        let classes = crate::runtime_src::parse_library_with_rbs(
            ruby.as_bytes(),
            rbs,
            "action_view/view_helpers.rb",
        )
        .expect("view_helpers parses and types");
        crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes
                .iter()
                .map(|c| emit_library_class(c).expect("emits"))
                .collect()
        })
    }

    fn emit_action_controller() -> String {
        let ruby = include_str!("../../../runtime/ruby/action_controller/base.rb");
        let rbs = include_str!("../../../runtime/ruby/action_controller/base.rbs");
        let classes = crate::runtime_src::parse_library_with_rbs(
            ruby.as_bytes(),
            rbs,
            "action_controller/base.rb",
        )
        .expect("action_controller/base parses and types");
        crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes
                .iter()
                .map(|c| emit_library_class(c).expect("emits"))
                .collect()
        })
    }

    fn method_body<'a>(src: &'a str, name: &str) -> &'a str {
        let needle = format!("pub fn {name}(");
        let start = src.find(&needle).unwrap_or_else(|| panic!("missing {name}:\n{src}"));
        let rest = &src[start..];
        let next = rest[needle.len()..]
            .find("\n    pub fn ")
            .map(|i| needle.len() + i)
            .unwrap_or(rest.len());
        &rest[..next]
    }

    /// `form_with` must stringify the Hash fetch before
    /// `method_override_input(&str)`.
    #[test]
    fn form_with_stringifies_method_before_override_input() {
        let src = emit_view_helpers();
        let body = method_body(&src, "form_with");
        assert!(
            body.contains("method_override_input") && body.contains("ruby_to_s"),
            "form_with must stringify the Hash fetch:\n{body}"
        );
        assert!(
            !body.contains("method_override_input(opts"),
            "gradual opts must not cross method_override_input:\n{body}"
        );
    }

    /// Column-union params render as `serde_json::Value`; `nil?` is
    /// `.is_null()`, not Option `.is_none()`.
    #[test]
    fn optional_value_attr_nil_check_uses_is_null() {
        let src = emit_view_helpers();
        let body = method_body(&src, "optional_value_attr");
        assert!(
            body.contains("is_null()"),
            "optional_value_attr nil? should be Value::is_null:\n{body}"
        );
        assert!(
            !body.contains("is_none()"),
            "optional_value_attr must not emit Option::is_none on Value:\n{body}"
        );
    }

    /// `to_s` on the column union must use fully-qualified UFCS.
    /// Method-style `.ruby_to_s()` needs `use RubyToS` in the file;
    /// ActionController does not import that trait, and a blanket
    /// `.ruby_to_s()` on every Value-rendering type broke compare rust.
    #[test]
    fn optional_value_attr_to_s_uses_ufcs() {
        let out = emit_view_helpers();
        let body = method_body(&out, "optional_value_attr");
        assert!(
            body.contains("<serde_json::Value as crate::http::RubyToS>::ruby_to_s"),
            "optional_value_attr to_s should be UFCS ruby_to_s:\n{body}"
        );
        assert!(
            !body.contains(".ruby_to_s()"),
            "method-style ruby_to_s needs the trait in scope:\n{body}"
        );
    }

    /// `turbo_stream_from`'s `String | Array[untyped]` renders as Value
    /// on rust only. Wrap scalar call-site args here, not in the shared
    /// lowerer — that Cast wrapping broke ActionController on extras.
    #[test]
    fn union_param_string_arg_wraps_as_value() {
        let ruby = r#"module VH
  def self.turbo_stream_from(stream, channel)
    stream.to_s + channel
  end
  def self.call
    turbo_stream_from("articles", "Turbo::StreamsChannel")
  end
end
"#;
        let rbs = r#"module VH
  def self.turbo_stream_from: (String | Array[untyped] stream, String channel) -> String
  def self.call: () -> String
end
"#;
        let classes = crate::runtime_src::parse_library_with_rbs(ruby.as_bytes(), rbs, "vh.rb")
            .expect("snippet parses and types");
        let out = crate::emit::rust::expr::with_emit_ctx(crate::emit::rust::EmitCtx::default(), || {
            classes
                .iter()
                .map(|c| emit_library_class(c).expect("emits"))
                .collect::<String>()
        });
        let body = method_body(&out, "call");
        assert!(
            body.contains("serde_json::Value::from") && body.contains("articles"),
            "string arg to String|Array union must wrap Value::from:\n{body}"
        );
    }

    /// Runtime emit uses an empty EmitCtx, so ActionController Const
    /// helpers must coerce from `external_class_method_param_tys`.
    /// HeaderStore `[]=` takes `Option<String>`, not Value.
    #[test]
    fn action_controller_runtime_emit_typechecks_hotspots() {
        let src = emit_action_controller();
        let set_index = method_body(&src, "set_index");
        assert!(
            set_index.contains("header_key_ok_pred(Some("),
            "header_key_ok? takes String?, wrap &str:\n{set_index}"
        );
        let val_at = method_body(&src, "val_at");
        assert!(
            val_at.contains("unwrap_or_default()"),
            "vals[i].to_s on Option must unwrap_or_default:\n{val_at}"
        );
        let render = method_body(&src, "render");
        assert!(
            render.contains("sanitize_location(&("),
            "sanitize_location takes &str, borrow the unwrapped String:\n{render}"
        );
        let send_data = method_body(&src, "send_data");
        assert!(
            send_data.contains("set_index(") && send_data.contains("Some("),
            "HeaderStore []= must wrap Option<String>, not Value::from:\n{send_data}"
        );
        assert!(
            !send_data.contains("Value::from"),
            "HeaderStore []= must not coerce through Value:\n{send_data}"
        );
        let csrf = method_body(&src, "request_for_csrf");
        assert!(
            csrf.contains("serde_json::Value::Null"),
            "untyped nil tail is Value::Null:\n{csrf}"
        );
    }
}
